# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

## COMMON
minecraftVersion=1.21.11
modVersion=1.0.3-1.21.11
mavenGroup=com.epherical.serverbrowser
modBaseArchiveName=ServerBrowser

## FABRIC
# check these on https://fabricmc.net/develop/
fabricLoaderVersion=0.19.3
fabricAPIVersion=0.139.4+1.21.11
fabricFancyMenuID=367706
fabricFancyMenuFile=8089437
fabricKonkreteID=410295
fabricKonkreteFile=7561074

## FORGE (not supported on 1.21.11, skipped)
# forgeVersion=44.1.0
# forgeFancyMenuID=367706
# forgeFancyMenuFile=4422141
# forgeKonkreteID=410295
# forgeKonkreteFile=4203299

## Other Dependencies
mixinVersion=0.8.5
JBAnnotationsVersion=23.1.0
parchmentVersion=2024.11.17
